# Generated by Django 5.2.8 on 2025-11-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out'), ('BREAK_START', 'Start Break'), ('BREAK_END', 'End Break')], max_length=12)),
                ('date_only', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
            },
        ),
        migrations.CreateModel(
            name='TimeEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_timestamp', models.DateTimeField(help_text='The new date and time the user wants the entry set to.')),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edits', to=settings.AUTH_USER_MODEL)),
                ('original_entry', models.ForeignKey(help_text='The original TimeEntry record being requested for change.', on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='time_tracker.timeentry')),
            ],
        ),
    ]
